version: '3.7'

services:
    app:
        build:
            context: ./docker/app
            dockerfile: Dockerfile
        networks:
            - app_network
        volumes:
            - .:/var/www/html
        ports:
            - 8080:80
        working_dir: /var/www/html

    swagger:
        image: swaggerapi/swagger-ui:latest
        networks:
            - app_network
        volumes:
            - ./docs/api:/usr/share/nginx/html/docs/
        ports:
            - 8085:8080
        environment:
            - URLS=[{"url":"/docs/openapi.yaml","name":"DEVELOPMENT"}]

    db:
        image: "postgres:13"
        environment:
            - POSTGRES_PASSWORD=mysecretpassword
            - POSTGRES_USER=root
            - POSTGRES_DB=app
        ports:
            - 5432:5432
        volumes:
            - db_data:/var/lib/postgresql/data
        networks:
            - app_network

    test_db:
        image: "postgres:13"
        environment:
            - POSTGRES_PASSWORD=mysecretpassword
            - POSTGRES_USER=root
            - POSTGRES_DB=app
        ports:
            - 5432
        networks:
            - app_network

volumes:
    db_data:
        driver: local

networks:
    app_network:
        driver: bridge

