version: '3.5'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    networks:
      - appnet
    ports:
      - "2181"
    hostname: zookeeper

  kafka:
    image: wurstmeister/kafka
    command: [start-kafka.sh]
    ports:
      - 9092:9092
    hostname: kafka
    networks:
      - appnet
    environment:
      KAFKA_MAX_REQUEST_SIZE: 20000000
      KAFKA_MESSAGE_MAX_BYTES: 200000000
      KAFKA_REPLICA_FETCH_MAX_BYTES: 200000000
      KAFKA_MAX_MESSAGE_BYTES: 200000000
      KAFKA_FETCH_MESSAGE_MAX_BYTES: 200000000
      KAFKA_CREATE_TOPICS: "test:1:1" # topic:partition:replicas
      KAFKA_ADVERTISED_HOST_NAME: kafka # docker-machine ip
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_PORT: 9092
    working_dir: /opt/kafka
    depends_on:
      - "zookeeper"

networks:
  appnet:
    external: true
    name: diana_appnet
